spring:
    jpa:
        show-sql: true
    datasource-write:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5434/demo_replication
        username: postgres_db_admin
        password: master@12345
        platform: postgresql
        hikari:
            idle-timeout: 10000
            maximum-pool-size: 2
            minimum-idle: 1
            pool-name: WriteHikariPool
    datasource-read:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5435/demo_replication
        username: postgres_db_admin
        password: master@12345
        platform: postgresql
        hikari:
            idle-timeout: 10000
            maximum-pool-size: 2
            minimum-idle: 1
            pool-name: WriteHikariPool                